version: '3'

services:
  php:
    build: ./php
    ports:
      - "5173:5173"
    volumes:
      - ../:/var/www

  nginx:
    image: nginx:1.20-alpine
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    build: ./mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
